CC      = clang
CFLAGS  = -O2 -Wall -Wextra -std=c99 -Isrc \
          $(shell pkg-config --cflags wayland-client wayland-cursor cairo xkbcommon)
LIBS    = $(shell pkg-config --libs   wayland-client wayland-cursor cairo xkbcommon) \
          -lwebp -lm
# CFLAGS += -DDEBUG

PREFIX  = /usr/local
BINDIR  = $(PREFIX)/bin
BINARY  = whot

# Protocol-generated glue (generated by `make protocols`)
PROTO_SRCS = \
    src/xdg-shell-protocol.c \
    src/wlr-layer-shell-unstable-v1-protocol.c \
    src/wlr-screencopy-unstable-v1-protocol.c

SRCS = main.c \
       src/wutil.c \
       src/capture.c \
       src/save.c \
       src/scripts.c \
       src/select.c \
       $(PROTO_SRCS)

OBJS = $(SRCS:.c=.o)
DEPS = $(OBJS:.o=.d)

-include $(DEPS)

all: $(BINARY)

$(BINARY): $(OBJS)
	$(CC) $(OBJS) -o $@ $(LIBS)

%.o: %.c
	$(CC) $(CFLAGS) -MMD -MP -c $< -o $@

# Regenerate protocol glue from XMLs (requires wayland-scanner).
# Pre-generated files are already in src/, so this target is optional.
protocols:
	wayland-scanner client-header \
	    /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml \
	    src/xdg-shell-client-protocol.h
	wayland-scanner private-code \
	    /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml \
	    src/xdg-shell-protocol.c
	wayland-scanner client-header \
	    protocols/wlr-layer-shell-unstable-v1.xml \
	    src/wlr-layer-shell-unstable-v1-client-protocol.h
	wayland-scanner private-code \
	    protocols/wlr-layer-shell-unstable-v1.xml \
	    src/wlr-layer-shell-unstable-v1-protocol.c
	wayland-scanner client-header \
	    protocols/wlr-screencopy-unstable-v1.xml \
	    src/wlr-screencopy-unstable-v1-client-protocol.h
	wayland-scanner private-code \
	    protocols/wlr-screencopy-unstable-v1.xml \
	    src/wlr-screencopy-unstable-v1-protocol.c

install: $(BINARY)
	install -Dm755 $(BINARY) $(DESTDIR)$(BINDIR)/$(BINARY)

uninstall:
	rm -f $(DESTDIR)$(BINDIR)/$(BINARY)

clean:
	rm -f $(OBJS) $(DEPS) $(BINARY) src/xdg-shell-protocol.o src/xdg-shell-protocol.d

.PHONY: all protocols install uninstall clean
